# Generated by Django 6.1.2 on 2026-10-10 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=80, unique=True)),
                ("name", models.CharField(max_length=200, verbose_name="system name")),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("DCB0160", "DCB0160 - deploying a system"),
                            ("DCB0129", "DCB0129 - manufacturing a system"),
                        ],
                        default="DCB0160",
                        max_length=10,
                    ),
                ),
                ("organisation", models.CharField(max_length=200, verbose_name="organisation")),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="private",
                        help_text="Transparency is the long-term goal, but visibility defaults to private because publishing is a governance decision and the safe default for an unreviewed draft is not to publish it.",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Accountable for this safety file. PROTECT rather than CASCADE: deleting a user must never delete safety evidence.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="safety_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "safety file",
                "verbose_name_plural": "safety files",
                "ordering": ["name"],
            },
        ),
    ]
