site_name: Turva Documentation
site_url: https://turva-uk.github.io/turva/
repo_url: https://github.com/turva-uk/turva
copyright: Copyright &copy; 2026 Turva

theme:
  variant: classic
  navigation_depth: 4

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            heading_level: 2

nav:
  - Introduction: index.md
  - Getting started: getting-started.md
  - Technical overview: technical-overview.md

  - Code Reference:
      - Safety file storage layer: code/safety-file/index.md
