"""empty message

Revision ID: 0ca458ce603b
Revises: fba79f275bab
Create Date: 2025-10-20 20:17:19.731878

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ca458ce603b"
down_revision: str | Sequence[str] | None = "fba79f275bab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "tbl_session", ["id"])
    op.alter_column(
        "tbl_user",
        "verification_token_created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.create_unique_constraint(None, "tbl_user", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tbl_user", type_="unique")
    op.alter_column(
        "tbl_user",
        "verification_token_created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "tbl_session", type_="unique")
    # ### end Alembic commands ###
