"""empty message

Revision ID: 68d1f971a3c2
Revises: 0ca458ce603b
Create Date: 2025-10-24 09:42:17.737250

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68d1f971a3c2"
down_revision: str | Sequence[str] | None = "0ca458ce603b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tbl_user", sa.Column("is_cso", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tbl_user", "is_cso")
    # ### end Alembic commands ###
